### PR TITLE
Added Youtube Inline + upstreams and bug fixes

### PR DESCRIPTION
**Pull request by code-rgb**

### CODE REVIEW

**Comment by niteshraj2310** [comment]
@vercel[bot] wew

**Comment by code-rgb** [comment]
@niteshraj2310

**Comment by niteshraj2310** [comment]
@code-rgb

**Comment by Guru-25** [comment]
@niteshraj2310 Any tuto for Downloading utube videos in inline?

**Comment by Guru-25** [comment]
@Guru-25 Wtf 😳

**Comment by F36** [comment]
@Guru-25 Naruhudo

**Comment by Guru-25** [comment]
@Guru-25 How the bot knowns my git id?

**Comment by F36** [comment]
@Guru-25 Because you connected your account with it

**Pull request merged**
