### PR TITLE
Update whois.py

### PR DESCRIPTION
**Pull request by adityeah001**

### CODE REVIEW

**Comment by code-rgb** [comment]
👀 I'm Confused

**Comment by TomyPrs** [comment]
@code-rgb Nice code son

**Comment by Mr-PerfectPURUSHOTTAM** [comment]
What is that?🙄

**Comment by hostingthepage** [comment]
@TomyPrs Is the admin your son ?

**Comment by F36** [comment]
@TomyPrs

**Comment by Mr-PerfectPURUSHOTTAM** [comment]
Abe ye q aa rhe emails

**Comment by code-rgb** [comment]
> @TomyPrs Is the admin your son ?

Read it again

**Pull request closed without merging**
